### ISSUE TITLE
Add g2/python/requirements.txt to enumerate packages used across all G2Tools

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2-python#125]
See https://github.com/Senzing/community-roadmap/issues/56

This issue is for creating a `requirements.txt` that goes into https://github.com/Senzing/g2-python/tree/main/g2/python

**Comment by jbutcher21** [comment]
Need prettytable-3.2.0 for  >= senzing 3.x, and the ptable you currently installing in sshd container for prior versions
   If not possible, just keep installing ptable, user can add prettytable manually if they want it even prettier.

For database access we need ...
* psycopg2 for postgres, 
* pyodbc for everything else.   
* will need something new for oracle when we get there.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/g2-python/pull/127
