### ISSUE TITLE
Add send-to-file / send-prior-to-file and clipboard to G2Command & G2ConfigTool

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#86]

**Comment by docktermj** [comment]
Should be issues in https://github.com/Senzing/g2command and https://github.com/Senzing/g2configtool rather than this repository.

**Comment by docktermj** [comment]
Moved to:

1. https://github.com/Senzing/g2command/issues/37
2. https://github.com/Senzing/g2configtool/issues/31
