### ISSUE TITLE
G2Command.py should have better help documentation on flags

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#89]
Jonas has asked that we improved the documentation around "flags" inside of G2Command.py.  He noted the following command and example, where flags were mentioned, but no info was given.

(g2) 
(g2) exportCSVEntityReport
G2Command > exportEntityReport: error: the following arguments are required: -f/-flags

Export repository contents as CSV:  exportCSVEntityReport -f <flags> [-o <output_file>]

(g2)

**Comment by docktermj** [comment]
Should be an issue in https://github.com/Senzing/g2command rather than this repository.

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2command/issues/36
