### ISSUE TITLE
Additional G2Command functionality

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#90]
- [ ] Pretty print
- [ ] Colour pretty print
- [ ] New processResponse() function and associated helper functions
- [ ] Update docstrings with examples
- [ ] Copy to file and/or clipboard capabilities 
- [ ] Auto completers

**Comment by docktermj** [comment]
Should be an issue in https://github.com/Senzing/g2command rather than this repository.

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2command/issues/35
