### ISSUE TITLE
Update videos/docs for quickstarts etc

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#91]
Basic mapping and loading with G2Loader

Video 1: https://senzing.zendesk.com/hc/en-us/articles/115007461148-Video-Mapping-and-Loading-Part-1

Video 2: https://senzing.zendesk.com/hc/en-us/articles/115007708808-Video-G2-Mapping-and-Loading-Part-2

Advanced Mapping Concepts (review both the video and guide)

Video: https://www.youtube.com/watch?v=2ethEN8alqY&feature=youtu.be

Guide: https://senzing.zendesk.com/hc/en-us/articles/360054097153-Advanced-mapping-concepts

**Comment by docktermj** [comment]
Should be an issue in https://github.com/Senzing/g2loader rather than this repository.

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2loader/issues/43
