### ISSUE TITLE
Improve G2SetupConfig - error to set default config doesn't tell you why it fails

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#92]
```
--> ./G2SetupConfig.py 

A configuration document already exists in the database.  Do you want to replace it (yes/no)?  y

Installing template configuration to database.  Do you want to continue (yes/no)?  y
Error:  Failed to set config as default.
```

Great, but why? 

I doubt G2Setup has been looked at in a while, I'll give it a going over when correcting the above.

**Comment by docktermj** [comment]
Should be an issue in https://github.com/Senzing/g2setupconfig rather than this repository.

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2setupconfig/issues/15
