### ISSUE TITLE
Improve G2CreateProject in situation where unreadable objects have been placed in /opt/senzing/

### ISSUE THREAD

**Issue by antaenc** [Senzing/g2-python#97]
See https://senzing.zendesk.com/agent/tickets/3854

Shouldn't really happen but it did, wrap in supress of try and display what went wrong but continue with normal senzing objects.

**Comment by docktermj** [comment]
Should be an issue in https://github.com/Senzing/g2createproject rather than this repository.

**Comment by docktermj** [comment]
Moved to https://github.com/Senzing/g2createproject/issues/17
